config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  resources :users do
    member do
      get 'account'
    end
    collection do
      get 'search'
    end
    get 'users/:account',controller: 'users', action: 'show'
  end
  resources :rooms do
    collection do
      get :'search'
      get :'top'
      get :'allroom'
    end
  end
  resources :reservations do
    collection do
      post :confirm
    end
  end  
  
  root to: "rooms#top"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :profileimage,ProfileimageUploader
  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy
       
  def already_reservated?(user)
    self.reservations.exists?(room_id: room.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!,except: [:index,:show]

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def account
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: '不正なアクセスです'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "#{@user.id}の情報を更新しました"
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:profileimage, :username, :profile)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="container-fuluid"> 
  <div class="container" >
    <div class="mt-4">
      <div class="row">
          <%= link_to "プロフィール", user_path(@user),class:"col-md-6 lead"%>
          <p class="col-md-6 lead border-bottom">アカウント</p>
      </div>
    </div>
    
    <div class="mt-5">
      <div class="row">
        <div class="col-md-3">
          <p>e-mail</p>
        </div>
        <div class="col-md-5">
          <%= @user.email%>
        </div>
      </div>
    </div>
    <div class="mt-5">
      <div class="row">
        <div class="col-md-3">
          <p>パスワード</p>
        </div>
        <div class="col-md-5">
          <p>******</p>
        </div>
      </div>
    </div>
    <%= link_to '編集', edit_user_registration_path, class:"btn btn-primary" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class= container> 
  <div class="mb-5"> 
    <h1>プロフィール設定</h1>
  </div>
  <section class="section">
    <div class="container">
      <%= form_for @user do |f| %>
      <div class="mb-5">
        <div class="row">
          <%= f.label :profile_image, "プロフィール画像", class:"col-md-4" %>
          <%= f.file_field :profileimage, class:"col-md-6" %>
        </div>
      </div>
      <div class="mb-5">
        <div class="row">
          <%= f.label :username, "ユーザーネーム", class:"col-md-4"%>
          <%= f.text_field :username, class:"col-md-5" %>
        </div>
      </div>
      <div class="mb-5">
        <div class="row">
          <%= f.label :profile, "プロフィール", class:"col-md-4" %>
          <%= f.text_field :profile, class:"col-md-5" %>
        </div>
      </div>
      
        <div class="form-group">
          <%= f.submit('更新', class:'btn btn-primary mt-3 col-md-9')%>
        </div>
      <% end%>

      <%= link_to'キャンセル',user_path(@user), class:"btn btn-outline-dark col-md-9" %>
    </div>
  </section>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="text-center mt-5">
    <%= search_form_for @q,url: rooms_path do |f| %>
    <%= f.search_field :roomname_or_detail_or_address_cont,placeholder:"エリア検索"%>
    <%= f.submit '検索'%>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fuluid"> 
  <div class="container" >
    <div class="mt-4">
      <div class="row">
         <p class="col-md-6 lead border-bottom">プロフィール</p>
          <%= link_to "アカウント", account_user_path(@user), class:"col-md-6 lead"%>
      </div>
    </div>
      <div class="mt-5">
       <div class="row">
          <div class="col">
            <%= image_tag current_user.profileimage.url,size:"50x50" %>   
          </div>
        </div>
      </div>
      <div class="mt-5">
        <div class="row">
          <div class="col-md-3">
            <p>ユーザーネーム</p>
          </div>
          <div class="col-md-5">
            <%= @user.username %>
          </div>
        </div>
      </div>
      <div class="mt-5">
        <div class="row">
          <div class="col-md-3">
            <p>プロフィール</p>
          </div>
          <div class="col-md-5">
            <%= @user.profile %>
          </div>
        </div>
        <%= link_to '編集', edit_user_path(@user), class:"btn btn-primary" %>
    </section>
  </div>
</div>