config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  resources :users do
    member do
      get 'account'
    end
    collection do
      get 'search'
    end
    get 'users/:account',controller: 'users', action: 'show'
  end
  resources :rooms do
    collection do
      get :'search'
      get :'top'
      get :'allroom'
    end
  end
  resources :reservations do
    collection do
      post :confirm
    end
  end  
  
  root to: "rooms#top"
end

app/views/shared/_form.html.erb
<%= form_with model: @form, local: true do |f| %>

  <div class="field">
    <%= f.label :date, "日付" %>
    <%= f.date_select :date, use_month_numbers: true, start_year: Time.now.year - 20, end_year: Time.now.year %>

    <%= render "layouts/error_messages", model: @form, attribute: :date %>
  </div>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm  navbar-dark bg-dark">
    <div class="navbar-brand">
      <h2 class= "text-light"><%= link_to "Potepan Share",top_rooms_path,class:'text-secondary'%></h2>
    </div>

    <ul class="collapse navbar-collapse justify-content-end">
      <% if user_signed_in? %> 
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" 
            href="#" 
            id="navbarDropdown" 
            role="button" 
            data-toggle="dropdown" 
            aria-haspopup="true" 
            aria-expanded="false">

            <%= image_tag current_user.profileimage.url,size:"50x50" %>
            <%= current_user.username %>
          </a>  
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%=link_to"施設の新規登録", new_room_path,class: "text-secondary", class:"dropdown-item"%>
            <%=link_to"施設一覧",  allroom_rooms_path,class: "text-secondary", class:"dropdown-item"%>    
            <%= link_to "アカウント確認", user_path(current_user), class:"dropdown-item" %>
            <%= link_to"予約情報確認",  reservation_path(current_user), class:"dropdown-item" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-secondary", class:"dropdown-item" %>
          </div>
        </div>
           
      <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "text-light"  %>
        <%= link_to "新規登録", new_user_registration_path, class: "text-light" %>
      <% end %>
    </ul>
  </nav>
</header>