config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  resources :users do
    member do
      get 'account'
    end
    collection do
      get 'search'
    end
    get 'users/:account',controller: 'users', action: 'show'
  end
  resources :rooms do
    collection do
      get :'search'
      get :'top'
      get :'allroom'
    end
  end
  resources :reservations do
    collection do
      post :confirm
    end
  end  
  
  root to: "rooms#top"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  mount_uploader :image, ImageUploader
  
  with_options presence: true do
    validates :user_id
    validates :room_id
    validates :check_in
    validates :check_out
    validates :number
  end
  
  validates :number,numericality: {only_integer: true,greater_than_to: 0}

  validate :start_end_check

  def start_end_check
    unless check_in == nil || check_out ==nil
    errors.add(:check_out, "は開始日より後のものを選択してください") unless
    self.check_in < self.check_out
    end
  end

  def total
    (self.check_out - self.check_in).to_i * self.number.to_i * self.price.to_i
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!

  def index
  end

  def show
    @reservations = Reservation.where(user_id: current_user.id)
  end

  def new
    @reservation = Reservation.new
  end

  def confirm
    @room = Room.find(params[:reservation][:room_id])
    @reservation = Reservation.new(reservation_params)
    if @reservation.invalid?
      render template: "rooms/show"
      return
    end
   
  end

  def create
    @reservation = Reservation.new(reservation_params)
    render template: "rooms/show"  and return if  !@reservation.save 
    redirect_to @reservation
  end 

  private

  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out, :number, :room_id, :user_id, :created_at,:price)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/confirm.html.erb
<div class="container-fuluid"> 
  <div class="container" >
    <div class="mt-5">
        <div class="row">
          <div class="col-md-3">
            <p>施設名</p>
          </div>
          <div class="col-md-5">
            <%= @reservation.room.roomname %>
          </div>
        </div>
      </div>
      <div class="mt-5">
        <div class="row">
          <div class="col-md-3">
            <p>開始日</p>
          </div>
          <div class="col-md-5">
            <%= @reservation.check_in %>
          </div>
        </div>
      </div>
      <div class="mt-5">
        <div class="row">
          <div class="col-md-3">
            <p>終了日</p>
          </div>
          <div class="col-md-5">
            <%= @reservation.check_out %>
          </div>
        </div>
      </div>
      <div class="mt-5">
        <div class="row">
          <div class="col-md-3">
            <p>人数</p>
          </div>
          <div class="col-md-5">
            <%= @reservation.number %>
          </div>
        </div>
      </div>
      <div class="mt-5">
        <div class="row">
          <div class="col-md-3">
            <p>支払い金額</p>
          </div>
          <div class="col-md-5">
            <p>¥<%= @reservation.total %></p>
          </div>
        </div>
      </div>
  </div>

  <%= form_with(model:@reservation, method: :post, url: reservations_path) do |f|%>
    <%= f.hidden_field :user_id %>
    <%= f.hidden_field :room_id %>
    <%= f.hidden_field :check_in %>
    <%= f.hidden_field :check_out %>
    <%= f.hidden_field :number %>
    <%= f.hidden_field :price %>
    <%= f.submit '登録する', class:'btn-warning mt-3 col-md-9'%>
  <% end %>

  <%= link_to "Back", :back,class:"btn btn-outline-dark  mt-3 col-md-9" %>
</div>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/new.html.erb
<%= form_with model: @reservation do |f| %>
  <div class="container"> 
    <div class="mb-5"> 
      <h1>施設予約</h1>
      
      <%= f.hidden_field :room_id, value: @room %>
    </div>
      <div class="mb-5">
        <div class="row">
          <%= f.label :check_in, class:"mr-3" %>
          <%= f.text_field :check_in,class:"ml-3"%>
          
        </div>
      </div>

      <div class="mb-5">
        <div class="row">
          <%= f.label :check_out,class:"mr-3"%>
          <%= f.text_field :check_out %>
        </div>
      </div>

      <div class="mb-5">
        <div class="row">
          <%= f.label :number,class:"mr-5"%><br />
          <%= f.text_field :number %>
        </div>
      </div>

      

      <div class="actions">
        <%= f.submit "保存", class: 'btn btn-primary col-md-9' %>
      </div>
  </div>
<% end %>

<%= link_to "Back", :back,class:"btn btn-outline-dark  mt-3 col-md-9" %>

app/views/reservations/show.html.erb
<h3>予約一覧</h3>
<table>
 <thead>
    <tr>
      <th></th>
      <th class=col-3>施設名</th>
      <th class=col-2>詳細</th>
      <th class=col-2>住所</th>
      <th class=col-2>料金</th>
      <th class=col-3>開始日</th>
      <th class=col-3>終了日</th>
      <th class=col-4>人数</th>
      <th class=col-4>予約確定日</th>
    </tr>
 </thead>

  <tbody>    
    <tr> 
      <% @reservations.each do |reservation|%>
      <td><%= image_tag reservation.room.image.to_s, size:"50x50"%></td> 
      <td class="col-3"><%= link_to reservation.room.roomname, room_path(reservation.room_id) %></td>
      <td class=col-2><%= reservation.room.detail %></td>
      <td class=col-2><%= reservation.room.address %></td>
      <td class=col-2>¥<%= reservation.total %></td>
      <td class=col-3><%= reservation.check_in.to_s(:creteatime_jp) %></td>
      <td class=col-3><%= reservation.check_out.to_s(:creteatime_jp) %></td>
      <td class=col-4><%= reservation.number %></td>
      <td class=col-4><%= reservation.created_at.to_s(:datetime_jp) %></td>
    </tr>  
      <% end %>
  </tbody>
</table>