config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  resources :users do
    member do
      get 'account'
    end
    collection do
      get 'search'
    end
    get 'users/:account',controller: 'users', action: 'show'
  end
  resources :rooms do
    collection do
      get :'search'
      get :'top'
      get :'allroom'
    end
  end
  resources :reservations do
    collection do
      post :confirm
    end
  end  
  
  root to: "rooms#top"
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user,optional: true
  has_many :reservations, dependent: :destroy
  
  mount_uploader :image, ImageUploader

  with_options presence: true do
    validates :roomname
    validates :detail
    validates :price
    validates :address
  end
  
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}


  def self.search_area(area)
     where(["address like?", "%#{area}%"])  
  end
 
  def self.search(keyword) 
    where(["roomname like? OR price like? OR detail like? OR address like?","%#{keyword}%","%#{keyword}%","%#{keyword}%","%#{keyword}%"]) 
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!, except: [:index,:show,:top,:search ]
  helper_method :current_user

  def index
    @rooms = Room.all
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
    if @rooms.count > 0
      flash.now[:alert] = "#{@rooms.count}件の検索結果"
    else
      flash.now[:alert] = "検索結果が見つかりませんでした"
    end
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "新規登録しました"
      redirect_to room_path(@room)
    else
      render"new"
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @room = Room.find(params[:id])
    if @room.user_id != current_user.id
      redirect_to room_path, alert: '編集権限がありません'
    end
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(params.require(:room).permit(:roomname, :detail, :price, :address, :image, :image_cache))
    redirect_to room_path(@room)
    else
      render"edit"
    end
  end

  def search 
    if params[:area].present?
      @rooms = Room.search_area(params[:area])
      if @rooms.count > 1
        flash.now[:alert] = "#{@rooms.count}件の検索結果"
        render'index'
      else
        flash.now[:alert] = "検索結果が見つかりませんでした"
        render'index'
      end
    elsif params[:keyword].present?
      @rooms = Room.search(params[:keyword])
      if @rooms.count > 0
        flash.now[:alert] = "#{@rooms.count}件の検索結果"
        render'index'
      else
        flash.now[:alert] = "検索結果が見つかりませんでした"
        render'index'
      end
    else
      @rooms = Room.all
      flash.now[:alert] = "#{@rooms.count}件の検索結果"
        render'index'
    end  
  end

  def top
    @q = Room.ransack(params[:q])
  end

  def allroom
    @rooms = Room.where(user_id: current_user.id).order("created_at DESC")
    render'index'
  end


  private
  def room_params
    params.require(:room).permit(:user_id, :roomname, :detail, :price, :address, :image, :image_cache)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class= container> 
  <% if @room.errors.any? %>
    <%= @room.errors.full_messages.each do |message|%>
    <% end %>
  <% end %>

  <div class="mb-5"> 
    <h1>施設情報編集</h1>
  </div>

  <section class="section">
    <div class="container">
      <%= form_with model: @room, url: room_path(@room),local: true do |f| %>
        <div class="mb-5">
          <div class="row">
            <%= f.label :roomname, "施設名", class:"col-md-4" %>
            <%= f.text_field :roomname,class:"col-md-5" %>
          </div>
        </div>
        <div class="mb-5">
          <div class="row">
            <%= f.label :detail,"施設詳細", class:"col-md-4"%>
            <%= f.text_area :detail, class:"col-md-5" %>
          </div>
        </div>
        <div class="mb-5">
          <div class="row">
            <%= f.label :price, "価格", class:"col-md-4" %>
            <%= f.text_field :price, class:"col-md-5" %>
          </div>
        </div>
        
        <div class="mb-5">
          <div class="row">
            <%= f.label :address, "住所", class:"col-md-4" %>
            <%= f.text_field :address, class:"col-md-5" %>
          </div>
        </div>

        <div class="mb-5">
          <div class="row">
            <%= f.label :image, "施設画像", class:"col-md-4" %>
            <%= f.file_field :image %>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit('保存', class:'btn btn-primary mt-3 col-md-9')%>
        </div>
      <% end %>

      <%= link_to'キャンセル',:back, class:"btn btn-outline-dark col-md-9" %>
    </div>
  </section>
</div>

app/views/rooms/index.html.erb
<head>
    <div class="search_form center-block">
      <%= form_with url: search_rooms_path, method: :get, local: :true do |f|  %>
        <%= f.text_field :area, placeholder:"エリア検索", value: @aria %>
        <%= f.text_field :keyword, placeholder:"キーワード検索", value: @keyword %>
        <%= f.submit "検索", class: "btn"%>
      <% end %>
    </div>
</head>
<body>
  <% @rooms.each do |room|%> 
    <main>
      <div class="album py-4 bg-light">
        <div class="container">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col-5">
              <div class="card shadow-sm">
                <%= image_tag room.image.to_s %>
                <div class="card-body">
                  <div class="card-text">
                    <p><%= room.roomname %></p>
                    <p><%= room.address %></p>
                    <p><%= room.detail %></p>  
                    <p>¥<%= room.price %>/日</p>
                    <p><%= room.created_at.to_s(:creteatime_jp) %></p>
                    <%= link_to "詳細はこちら", room,class:"btn btn-outline-dark" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  <% end %>
</body>

app/views/rooms/new.html.erb
<%= form_with model: @room do |f| %>
  <div class="container">
    <% if @room.errors.any? %>
        <%= @room.errors.full_messages.each do |message|%>
        <% end %>
    <% end %>

    <div class="mb-5"> 
      <h2>新規登録</h2>
    </div>
    
    <div class="mb-5">
      <div class="row">
        <%= f.label :roomname,"施設名", class:"mr-3" %>
        <%= f.text_field :roomname,class:"ml-3"%>
      </div>
    </div>

    <div class="mb-5">
      <div class="row">
        <%= f.label :detail,"施設詳細",class:"mr-3"%>
        <%= f.text_area :detail %>
      </div>
    </div>

    <div class="mb-5">
      <div class="row">
        <%= f.label :price,"料金",class:"mr-5"%><br />
        <%= f.text_field :price %>
      </div>
    </div>
    
    <div class="mb-5">
      <div class="row">
        <%= f.label :address,"住所",class:"mr-5"%> 
        <%= f.text_field :address %>
      </div>
    </div>

    <div class="mb-5">
      <div class="row">
        <%= f.label :image,"画像",class:"mr-5"%>
        <%= f.file_field :image %>
      </div>
    </div>
      
    <div class="actions">
      <%= f.submit "保存", class: 'btn btn-primary col-md-9' %>
    </div>
    
    <%= link_to "Back", :back,class:"btn btn-outline-dark  mt-3 col-md-9" %>
  </div>
<% end %>

app/views/rooms/search.html.erb
<head>
  <div class="search_form center-block">
    <%= form_with url: search_rooms_path, method: :get, local: :true do |f|  %>
      <%= f.text_field :area, placeholder:"エリア検索", value: @aria %>
      <%= f.text_field :keyword, placeholder:"キーワード検索", value: @keyword %>
      <%= f.submit "検索", class: "btn"%>
    <% end %>
  </div>
</head>

app/views/rooms/show.html.erb
<div class="container-fuluid"> 
  <div class="container" >
      <div class="row">
        <%= link_to "戻る", :back,class:"mt-3 col-9" %>
        <% if @room.user_id == current_user&.id%>
          <%= link_to "編集", edit_room_path(@room), class:"mt-3 col-2" %>
        <% end %>
      </div>
    <div class="mt-5">
      <div class="row">
        <%= image_tag @room.image.to_s %>
      </div>
    </div>
    <div class="mt-5">
      <div class="row">
        <div class="col-md-3">
          <%= @room.roomname %>
        </div>
      </div>
    </div>
    <div class="mt-5">
      <div class="row">
        <div class="col-md-3">
          <%= @room.address %>
        </div>
      </div>
    </div>
    <div class="mt-5">
      <div class="row">
        <div class="col-md-3">
          <%= @room.detail%>
        </div>
      </div>
    </div>

    <div class="mt-5">
      <div class="row">
        <div class="col-md-3">
         <p> ¥<%= @room.price%></p>
        </div>
      </div>
    </div>

    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>

     
    
    <h2 class="mt-5">施設を予約</h2>
    <%= form_with(model:@reservation, method: :post, url: confirm_reservations_path(@reservation)) do |f| %>
    <% if @reservation.errors.any? %>
    <% end %>
      <%= f.hidden_field :room_id, :value => @room.id %>
      <%= f.hidden_field :user_id, :value => current_user&.id %>
      <%= f.hidden_field :price, :value => @room.price %>
      <div class="row">
        <div class="col-3">
          <div class="form-group">     
            <%= f.label :check_in,"開始日" %>
            <%= f.date_field :check_in%>
            <% if @reservation.errors.include?(:check_in) %>
              <p style="color: red;"><%= @reservation.errors.full_messages_for(:check_in).first %>
            <% end %>
          </div>
        </div>
        <div class="col-3">
          <div class="form-group"> 
            <%= f.label :check_out,"終了日" %>
            <%= f.date_field :check_out %>
            <% if @reservation.errors.include?(:check_out) %>
              <p style="color: red;"><%= @reservation.errors.full_messages_for(:check_out).first %>
            <% end %>
          </div>
        </div>

        <div class="col-4">
          <div class="form-group">
            <%= f.label :number,"人数" %>
            <%= f.text_field :number %>
            <% if @reservation.errors.include?(:number) %>
              <p style="color: red;"><%= @reservation.errors.full_messages_for(:number).first %>
            <% end %>
          </div>
        </div>

        <div class="col-4">
          <div class="form-group">
            <%= f.submit "予約", class: 'btn btn-primary' %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/rooms/top.html.erb
<div class="container">
  <div class="text-center mt-5 mb-5">
    <%= search_form_for @q,url: rooms_path do |f| %>
      <%= f.search_field :roomname_or_detail_or_address_cont,placeholder:"エリア検索"%>
      <%= f.submit '検索'%>
    <% end %>
  </div>
  <div class="link_search">
    <h2 class="">おすすめのエリア</h2>
    <div class="form-inline">
      <%= link_to ({controller: "rooms", action: "index",q:{address_cont:"東京"}}) do%>
        <p class="link_tab tokyo" >東京</p>
      <% end %>
      <%= link_to ({controller: "rooms", action: "index",q:{address_cont:"大阪"}}) do%>
        <p class="link_tab">大阪</p>
      <% end %>
    </div>
    <div class="form-inline">
      <%= link_to ({controller: "rooms", action: "index",q:{address_cont:"京都"}}) do%>
        <p class="link_tab  kyoto">京都</p>
      <% end %>
      <div class="form-inline">
      <%= link_to ({controller: "rooms", action: "index",q:{address_cont:"札幌"}}) do%>
        <p class="link_tab">札幌</p>
      <% end %>
    </div>
  </div>
</div>